//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDU.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseDetail
    {
        public int Id { get; set; }
        public string Country { get; set; }
        public short Month { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string CustomerName { get; set; }
        public int Product { get; set; }
        public int Course { get; set; }
        public string Particulars { get; set; }
        public short Days { get; set; }
        public short NoPax { get; set; }
        public decimal LabRental { get; set; }
        public decimal SalesRev { get; set; }
        public string TrainerName { get; set; }
        public string DeliveredBy { get; set; }
        public Nullable<decimal> Airfare { get; set; }
        public string Hotel { get; set; }
        public Nullable<decimal> TrainerFee { get; set; }
        public string MISCLocal { get; set; }
        public Nullable<decimal> RegionalExpenses { get; set; }
        public string CourseMaterial { get; set; }
        public Nullable<decimal> TotalExp { get; set; }
        public Nullable<decimal> Profit { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public string RegionInvoice { get; set; }
        public string PaymentStatus { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
