//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDU.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentNumberHeader
    {
        public short BranchID { get; set; }
        public string DocumentID { get; set; }
        public string DocumentKey { get; set; }
        public string DocumentPrefix { get; set; }
        public short NumberLength { get; set; }
        public short LastNumber { get; set; }
        public bool UseCompany { get; set; }
        public bool UseBranch { get; set; }
        public bool UseYear { get; set; }
        public bool UseMonth { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    }
}
