//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDU.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentNumberDetail
    {
        public short BranchID { get; set; }
        public string DocumentKey { get; set; }
        public short YearNo { get; set; }
        public long January { get; set; }
        public long February { get; set; }
        public long March { get; set; }
        public long April { get; set; }
        public long May { get; set; }
        public long June { get; set; }
        public long July { get; set; }
        public long August { get; set; }
        public long September { get; set; }
        public long October { get; set; }
        public long November { get; set; }
        public long December { get; set; }
    }
}
