//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDU.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationalTransaction
    {
        public int OperationalTransactionId { get; set; }
        public int CategoryId { get; set; }
        public int ParticularsId { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<short> Month { get; set; }
        public decimal Amount { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public short Country { get; set; }
        public string CountryName { get; set; }
        public Nullable<int> OperationId { get; set; }
    }
}
