//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDU.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int RegistrationId { get; set; }
        public string OracleDataBase { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> WHT { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> Payment1 { get; set; }
        public Nullable<decimal> Payment2 { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Email { get; set; }
        public string Contact { get; set; }
        public string CompanyName { get; set; }
        public string Product { get; set; }
        public string CourseName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string TrainerName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
