//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDU.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int RegistrationId { get; set; }
        public string StudentName { get; set; }
        public string Email { get; set; }
        public string Contact { get; set; }
        public string CompanyName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<short> WHTPercent { get; set; }
        public Nullable<short> VATPercent { get; set; }
        public Nullable<decimal> WHTAmount { get; set; }
        public Nullable<decimal> VATAmount { get; set; }
        public Nullable<decimal> OtherDeductionsAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> Payment1 { get; set; }
        public Nullable<decimal> Payment2 { get; set; }
        public Nullable<decimal> Payment3 { get; set; }
        public Nullable<System.DateTime> Payment1Date { get; set; }
        public Nullable<System.DateTime> Payment2Date { get; set; }
        public Nullable<System.DateTime> Payment3Date { get; set; }
        public Nullable<short> Payment1Type { get; set; }
        public Nullable<short> Payment2Type { get; set; }
        public Nullable<short> Payment3Type { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
        public string TrainingConfirmationID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ChequeNo1 { get; set; }
        public string ChequeNo2 { get; set; }
        public string ChequeNo3 { get; set; }
    }
}
