//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDU.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Securable
    {
        public string SecurableItem { get; set; }
        public string GroupID { get; set; }
        public string Description { get; set; }
        public string ActionType { get; set; }
        public string Link { get; set; }
        public string Icon { get; set; }
        public int Sequence { get; set; }
        public int ParentSequence { get; set; }
    }
}
