//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDU.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingConfirmation
    {
        public int Id { get; set; }
        public string TrainingConfirmationID { get; set; }
        public int Product { get; set; }
        public int Course { get; set; }
        public short TotalNoOfDays { get; set; }
        public short NoOfStudents { get; set; }
        public bool Private { get; set; }
        public bool Public { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int TrianerId { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public short Country { get; set; }
        public bool LVC { get; set; }
    }
}
